from retic.runtime import *
from retic.guarded import *
from retic.typing import *
from random import randrange, shuffle, random, seed
from copy import deepcopy
from retic import List, Void, Tuple, Bool, Int, Float
from player import Player
min_val = 2
max_val = 7
turns = 10
stack_size = 5


class Dealer:
    retic_class_type = Class('Dealer', {'update_game': Function(NamedParameters([('self', Dyn), ('player', Dyn), ('stack_index', Dyn), ('stacks', Dyn)]), Dyn), '__init__': Function(NamedParameters([('self', Dyn), ('players', Dyn), ('bull_points', Dyn), ('cards_per_game', Dyn)]), Dyn), 'replace_card': Function(NamedParameters([('self', Dyn), ('card', Dyn), ('index', Dyn), ('stacks', Dyn)]), Dyn), 'output_scores': Function(NamedParameters([('self', Dyn)]), Dyn), 'create_stacks': Function(NamedParameters([('self', Dyn)]), Dyn), 'simulate_game': Function(NamedParameters([('self', Dyn)]), Dyn), 'create_deck': Function(DynParameters, Dyn), }, {})

    def __init__(self, players, bull_points, cards_per_game):
        retic_cast(self, Dyn, Object('', {}), '\ndealer.py:22:8: Cannot write to attribute deck in value %s because it is not an object. (code NON_OBJECT_WRITE)').deck = retic_cast(retic_cast(self, Dyn, Object('', {'create_deck': Dyn, }), '\ndealer.py:22:20: Accessing nonexistant object attribute create_deck from value %s. (code WIDTH_DOWNCAST)').create_deck, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:22:20: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(cards_per_game)
        retic_cast(self, Dyn, Object('', {}), '\ndealer.py:23:8: Cannot write to attribute players in value %s because it is not an object. (code NON_OBJECT_WRITE)').players = players
        retic_cast(self, Dyn, Object('', {}), '\ndealer.py:24:8: Cannot write to attribute bull_points in value %s because it is not an object. (code NON_OBJECT_WRITE)').bull_points = bull_points
        retic_cast(self, Dyn, Object('', {}), '\ndealer.py:25:8: Cannot write to attribute cards_per_game in value %s because it is not an object. (code NON_OBJECT_WRITE)').cards_per_game = cards_per_game
    __init__ = retic_cast(__init__, Dyn, Function(NamedParameters([('self', Dyn), ('players', Dyn), ('bull_points', Dyn), ('cards_per_game', Dyn)]), Dyn), "\ndealer.py:16:4: Function %s does not match specified type Function(['self:Dyn', 'players:Dyn', 'bull_points:Dyn', 'cards_per_game:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")

    def simulate_game(self):
        while (not (retic_cast(max, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:32:18: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(self, Dyn, Object('', {'bull_points': Dyn, }), '\ndealer.py:32:22: Accessing nonexistant object attribute bull_points from value %s. (code WIDTH_DOWNCAST)').bull_points) >= 66)):
            for (i, player) in retic_cast(enumerate, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:33:29: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(self, Dyn, Object('', {'players': Dyn, }), '\ndealer.py:33:39: Accessing nonexistant object attribute players from value %s. (code WIDTH_DOWNCAST)').players):
                hand = []
                for i in retic_cast(range, Dyn, Function(AnonymousParameters([Int, Dyn]), Dyn), "\ndealer.py:35:25: Expected function of type Function(['Int', 'Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(0, (i + (1 * 10))):
                    hand.append(retic_cast(self, Dyn, Object('', {'deck': Dyn, }), '\ndealer.py:36:32: Accessing nonexistant object attribute deck from value %s. (code WIDTH_DOWNCAST)').deck[i])
                retic_cast(player, Dyn, Object('', {}), '\ndealer.py:37:16: Cannot write to attribute cards in value %s because it is not an object. (code NON_OBJECT_WRITE)').cards = retic_cast(hand, List(Dyn), Dyn, '\ndealer.py:37:16: Right hand side of assignment was expected to be of type Dyn, but value %s provided instead. (code SINGLE_ASSIGN_ERROR)')
            stacks = retic_cast(retic_cast(self, Dyn, Object('', {'create_stacks': Dyn, }), '\ndealer.py:38:21: Accessing nonexistant object attribute create_stacks from value %s. (code WIDTH_DOWNCAST)').create_stacks, Dyn, Function(AnonymousParameters([]), Dyn), '\ndealer.py:38:21: Expected function of type Function([], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')()
            for i in retic_cast(range, Dyn, Function(AnonymousParameters([Int]), Dyn), "\ndealer.py:39:21: Expected function of type Function(['Int'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(turns):
                for j in retic_cast(range, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:40:25: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(len, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:40:31: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(self, Dyn, Object('', {'players': Dyn, }), '\ndealer.py:40:35: Accessing nonexistant object attribute players from value %s. (code WIDTH_DOWNCAST)').players)):
                    player = retic_cast(self, Dyn, Object('', {'players': Dyn, }), '\ndealer.py:41:29: Accessing nonexistant object attribute players from value %s. (code WIDTH_DOWNCAST)').players[j]
                    chosen_stack_index = retic_cast(retic_cast(player, Dyn, Object('', {'choose_correct_stack': Dyn, }), '\ndealer.py:42:41: Accessing nonexistant object attribute choose_correct_stack from value %s. (code WIDTH_DOWNCAST)').choose_correct_stack, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:42:41: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(stacks)
                    (p, s) = retic_cast(retic_cast(retic_cast(self, Dyn, Object('', {'update_game': Dyn, }), '\ndealer.py:43:27: Accessing nonexistant object attribute update_game from value %s. (code WIDTH_DOWNCAST)').update_game, Dyn, Function(AnonymousParameters([Dyn, Dyn, Dyn]), Dyn), "\ndealer.py:43:27: Expected function of type Function(['Dyn', 'Dyn', 'Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(player, chosen_stack_index, stacks), Dyn, Tuple(Dyn, Dyn), '\ndealer.py:43:20: Right hand side of assignment was expected to be of type Tuple(Dyn,Dyn), but value %s provided instead. (code SINGLE_ASSIGN_ERROR)')
                    retic_cast(self, Dyn, Object('', {'bull_points': Dyn, }), '\ndealer.py:44:20: Accessing nonexistant object attribute bull_points from value %s. (code WIDTH_DOWNCAST)').bull_points[j] = (retic_cast(self, Dyn, Object('', {'bull_points': Dyn, }), '\ndealer.py:44:20: Accessing nonexistant object attribute bull_points from value %s. (code WIDTH_DOWNCAST)').bull_points[j] + p)
                    stacks = s
        return retic_cast(retic_cast(self, Dyn, Object('', {'output_scores': Dyn, }), '\ndealer.py:46:15: Accessing nonexistant object attribute output_scores from value %s. (code WIDTH_DOWNCAST)').output_scores, Dyn, Function(AnonymousParameters([]), Dyn), '\ndealer.py:46:15: Expected function of type Function([], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')()
    simulate_game = retic_cast(simulate_game, Dyn, Function(NamedParameters([('self', Dyn)]), Dyn), "\ndealer.py:27:4: Function %s does not match specified type Function(['self:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")

    def create_deck(self, deck_size, bull_points=retic_cast(0.5, Float, Dyn, '\ndealer.py:48: Parameter <_ast.arg object at 0x1022bad30> has a default value %s which does not match specified type Dyn. (code DEFAULT_MISMATCH)'), order=retic_cast(0.5, Float, Dyn, '\ndealer.py:48: Parameter <_ast.arg object at 0x1022bad68> has a default value %s which does not match specified type Dyn. (code DEFAULT_MISMATCH)')):
        retic_cast(seed, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:57:8: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(bull_points)
        cards = []
        for i in retic_cast(range, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:59:17: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(deck_size):
            cards.append(retic_cast(((i + 1), retic_cast(randrange, Dyn, Function(AnonymousParameters([Int, Int]), Dyn), "\ndealer.py:60:33: Expected function of type Function(['Int', 'Int'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(min_val, max_val)), Tuple(Dyn, Dyn), Dyn, '\ndealer.py:60:12: Expected argument of type Dyn but value %s was provided instead. (code ARG_ERROR)'))
        s = (order or retic_cast(random, Dyn, Function(AnonymousParameters([]), Dyn), '\ndealer.py:61:21: Expected function of type Function([], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')())
        retic_cast(shuffle, Dyn, Function(AnonymousParameters([List(Dyn), Function(NamedParameters([]), Dyn)]), Dyn), "\ndealer.py:62:8: Expected function of type Function(['List(Dyn)', 'Function([], Dyn)'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(cards, (lambda : s))
        return retic_cast(cards, List(Dyn), Dyn, '\ndealer.py:63:8: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
    create_deck = retic_cast(create_deck, Dyn, Function(DynParameters, Dyn), '\ndealer.py:48:4: Function %s does not match specified type Function(DynParameters, Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)')

    def create_stacks(self):
        stacks = []
        for i in retic_cast(range, Dyn, Function(AnonymousParameters([Int]), Dyn), "\ndealer.py:73:17: Expected function of type Function(['Int'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(4):
            stacks.append(retic_cast([retic_cast(retic_cast(retic_cast(self, Dyn, Object('', {'deck': Dyn, }), '\ndealer.py:74:27: Accessing nonexistant object attribute deck from value %s. (code WIDTH_DOWNCAST)').deck, Dyn, Object('', {'pop': Dyn, }), '\ndealer.py:74:27: Accessing nonexistant object attribute pop from value %s. (code WIDTH_DOWNCAST)').pop, Dyn, Function(AnonymousParameters([]), Dyn), '\ndealer.py:74:27: Expected function of type Function([], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')()], List(Dyn), Dyn, '\ndealer.py:74:12: Expected argument of type Dyn but value %s was provided instead. (code ARG_ERROR)'))
        return retic_cast(stacks, List(Dyn), Dyn, '\ndealer.py:75:8: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
    create_stacks = retic_cast(create_stacks, Dyn, Function(NamedParameters([('self', Dyn)]), Dyn), "\ndealer.py:65:4: Function %s does not match specified type Function(['self:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")

    def output_scores(self):
        res = []
        for i in retic_cast(range, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:84:17: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(len, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:84:23: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(self, Dyn, Object('', {'players': Dyn, }), '\ndealer.py:84:27: Accessing nonexistant object attribute players from value %s. (code WIDTH_DOWNCAST)').players)):
            player_points = retic_cast(self, Dyn, Object('', {'bull_points': Dyn, }), '\ndealer.py:85:28: Accessing nonexistant object attribute bull_points from value %s. (code WIDTH_DOWNCAST)').bull_points[i]
            player_name = retic_cast(retic_cast(self, Dyn, Object('', {'players': Dyn, }), '\ndealer.py:86:26: Accessing nonexistant object attribute players from value %s. (code WIDTH_DOWNCAST)').players[i], Dyn, Object('', {'name': Dyn, }), '\ndealer.py:86:26: Accessing nonexistant object attribute name from value %s. (code WIDTH_DOWNCAST)').name
            res.append(retic_cast((player_name, player_points), Tuple(Dyn, Dyn), Dyn, '\ndealer.py:87:12: Expected argument of type Dyn but value %s was provided instead. (code ARG_ERROR)'))
        return retic_cast(res, List(Dyn), Dyn, '\ndealer.py:88:8: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
    output_scores = retic_cast(output_scores, Dyn, Function(NamedParameters([('self', Dyn)]), Dyn), "\ndealer.py:77:4: Function %s does not match specified type Function(['self:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")

    def update_game(self, player, stack_index, stacks):
        top_cards = retic_cast(list, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:97:20: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(map, Dyn, Function(AnonymousParameters([Function(NamedParameters([('stack', Dyn)]), Dyn), Dyn]), Dyn), '\ndealer.py:97:25: Expected function of type Function(["Function([\'stack:Dyn\'], Dyn)", \'Dyn\'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')((lambda stack: stack[(- 1)]), stacks))
        discarded_index = retic_cast(retic_cast(player, Dyn, Object('', {'discard': Dyn, }), '\ndealer.py:98:26: Accessing nonexistant object attribute discard from value %s. (code WIDTH_DOWNCAST)').discard, Dyn, Function(AnonymousParameters([]), Dyn), '\ndealer.py:98:26: Expected function of type Function([], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')()
        discarded = retic_cast(retic_cast(retic_cast(player, Dyn, Object('', {'cards': Dyn, }), '\ndealer.py:99:20: Accessing nonexistant object attribute cards from value %s. (code WIDTH_DOWNCAST)').cards, Dyn, Object('', {'pop': Dyn, }), '\ndealer.py:99:20: Accessing nonexistant object attribute pop from value %s. (code WIDTH_DOWNCAST)').pop, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:99:20: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(discarded_index)
        if (discarded[0] < retic_cast(min, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:100:26: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(list, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:100:30: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(map, Dyn, Function(AnonymousParameters([Function(NamedParameters([('card', Dyn)]), Dyn), Dyn]), Dyn), '\ndealer.py:100:35: Expected function of type Function(["Function([\'card:Dyn\'], Dyn)", \'Dyn\'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')((lambda card: card[0]), top_cards)))):
            bull_points = retic_cast(sum, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:101:26: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(list, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:101:30: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(map, Dyn, Function(AnonymousParameters([Function(NamedParameters([('card', Dyn)]), Dyn), Dyn]), Dyn), '\ndealer.py:101:35: Expected function of type Function(["Function([\'card:Dyn\'], Dyn)", \'Dyn\'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')((lambda card: card[1]), stacks[stack_index])))
            new_stacks = retic_cast(retic_cast(self, Dyn, Object('', {'replace_card': Dyn, }), '\ndealer.py:103:25: Accessing nonexistant object attribute replace_card from value %s. (code WIDTH_DOWNCAST)').replace_card, Dyn, Function(AnonymousParameters([Dyn, Dyn, Dyn]), Dyn), "\ndealer.py:103:25: Expected function of type Function(['Dyn', 'Dyn', 'Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(discarded, stack_index, stacks)
            return retic_cast((bull_points, new_stacks), Tuple(Dyn, Dyn), Dyn, '\ndealer.py:104:12: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
        else:
            my_stack = stacks[stack_index]
            if (retic_cast(len, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:107:15: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(my_stack) == stack_size):
                bull_points = retic_cast(sum, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:108:30: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(list, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:108:34: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(retic_cast(map, Dyn, Function(AnonymousParameters([Function(NamedParameters([('card', Dyn)]), Dyn), Dyn]), Dyn), '\ndealer.py:108:39: Expected function of type Function(["Function([\'card:Dyn\'], Dyn)", \'Dyn\'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)')((lambda card: card[1]), my_stack)))
                new_stacks = retic_cast(retic_cast(self, Dyn, Object('', {'replace_card': Dyn, }), '\ndealer.py:109:29: Accessing nonexistant object attribute replace_card from value %s. (code WIDTH_DOWNCAST)').replace_card, Dyn, Function(AnonymousParameters([Dyn, Dyn, Dyn]), Dyn), "\ndealer.py:109:29: Expected function of type Function(['Dyn', 'Dyn', 'Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(discarded, stack_index, stacks)
                return retic_cast((bull_points, new_stacks), Tuple(Dyn, Dyn), Dyn, '\ndealer.py:110:16: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
            else:
                new_stacks = retic_cast(deepcopy, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:112:29: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(stacks)
                retic_cast(retic_cast(new_stacks[stack_index], Dyn, Object('', {'append': Dyn, }), '\ndealer.py:113:16: Accessing nonexistant object attribute append from value %s. (code WIDTH_DOWNCAST)').append, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:113:16: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(discarded)
                return retic_cast((0, new_stacks), Tuple(Int, Dyn), Dyn, '\ndealer.py:114:16: A return value of type Dyn was expected but a value %s was returned instead. (code RETURN_ERROR)')
    update_game = retic_cast(update_game, Dyn, Function(NamedParameters([('self', Dyn), ('player', Dyn), ('stack_index', Dyn), ('stacks', Dyn)]), Dyn), "\ndealer.py:90:4: Function %s does not match specified type Function(['self:Dyn', 'player:Dyn', 'stack_index:Dyn', 'stacks:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")

    def replace_card(self, card, index, stacks):
        new_stacks = retic_cast(deepcopy, Dyn, Function(AnonymousParameters([Dyn]), Dyn), "\ndealer.py:124:21: Expected function of type Function(['Dyn'], Dyn) at call site but but value %s was provided instead. (code FUNC_ERROR)")(stacks)
        new_stacks[index] = retic_cast([card], List(Dyn), Dyn, '\ndealer.py:125:8: Right hand side of assignment was expected to be of type Dyn, but value %s provided instead. (code SINGLE_ASSIGN_ERROR)')
        return new_stacks
    replace_card = retic_cast(replace_card, Dyn, Function(NamedParameters([('self', Dyn), ('card', Dyn), ('index', Dyn), ('stacks', Dyn)]), Dyn), "\ndealer.py:116:4: Function %s does not match specified type Function(['self:Dyn', 'card:Dyn', 'index:Dyn', 'stacks:Dyn'], Dyn). Consider changing the type or setting it to Dyn. (code BAD_FUNCTION_INJECTION)")
Dealer = retic_cast(Dealer, Dyn, Class('Dealer', {'update_game': Function(NamedParameters([('self', Dyn), ('player', Dyn), ('stack_index', Dyn), ('stacks', Dyn)]), Dyn), '__init__': Function(NamedParameters([('self', Dyn), ('players', Dyn), ('bull_points', Dyn), ('cards_per_game', Dyn)]), Dyn), 'replace_card': Function(NamedParameters([('self', Dyn), ('card', Dyn), ('index', Dyn), ('stacks', Dyn)]), Dyn), 'output_scores': Function(NamedParameters([('self', Dyn)]), Dyn), 'create_stacks': Function(NamedParameters([('self', Dyn)]), Dyn), 'simulate_game': Function(NamedParameters([('self', Dyn)]), Dyn), 'create_deck': Function(DynParameters, Dyn), }, {}), "\ndealer.py:11:0: Class %s does not match specified type Class(Dealer, {'update_game': Function(['self:Dyn', 'player:Dyn', 'stack_index:Dyn', 'stacks:Dyn'], Dyn), '__init__': Function(['self:Dyn', 'players:Dyn', 'bull_points:Dyn', 'cards_per_game:Dyn'], Dyn), 'replace_card': Function(['self:Dyn', 'card:Dyn', 'index:Dyn', 'stacks:Dyn'], Dyn), 'output_scores': Function(['self:Dyn'], Dyn), 'create_stacks': Function(['self:Dyn'], Dyn), 'simulate_game': Function(['self:Dyn'], Dyn), 'create_deck': Function(DynParameters, Dyn)}, ). Consider changing the type or setting it to Dyn. (code BAD_CLASS_INJECTION)")
