;; This file was generated by the `with-cache` library on 2017-04-26
((("fa502e4388a96d02d21091dfe5b9789f" "bda6115eb60990dbe4a8cbf5e3f44f61" "a61eef52045c0903cb3846882a700c07" "1650ec728e88d3c094eb56310fd86677" "b07a05261c5c230bb654809ba582a76f")) (3) 0 () 0 () () (q 32 4 64 8 8))
