;; This file was generated by the `with-cache` library on 2017-04-26
((("de9577a7845875bb0c05f553b31ebd40" "83073cc263ab93360d47612ed8b5b7fe" "97945837049b32c33f70f080ba6cc660")) (3) 0 () 0 () () (q 16 2 1024))
