;; This file was generated by the `with-cache` library on 2017-04-26
((("d8836244bd9df6b3fc761ae0766a0371" "82ea78ffb5ddb45138eccb1dca74652a" "46143429807bdf157b515e2dd558d8b3" "cdf4ada4377a748af06669f25150fb4f" "162d6033afc0925c227f4151e5dcf68f" "0cf90f69283a45cdde30b58b70693650")) (3) 0 () 0 () () (q 8192 1 16 32 32 128))
