;; This file was generated by the `with-cache` library on 2017-04-26
((("248fb87ce9113a6128a6bf1ffe0cf70b" "2f636b25b5b25b564c541ef6904615b9" "177965d5de652375366cefa364a00fce")) (3) 0 () 0 () () (q 128 32 128))
