;; This file was generated by the `with-cache` library on 2017-04-26
((("c9e30cf708b37d0f300c29b2223881f8" "0e25bd26f84cf6500962a9fb3dfa8829" "616cff9da7e710cdec35b248109d62fc")) (3) 0 () 0 () () (q 256 8 32))
