;; This file was generated by the `with-cache` library on 2017-05-09
((("de9577a7845875bb0c05f553b31ebd40" "83073cc263ab93360d47612ed8b5b7fe" "9b21246c2d0a18ec3faaece1219ba2b1")) (3) 0 () 0 () () (q 16 2 1024))
