;; This file was generated by the `with-cache` library on 2017-04-26
((("b6bc8492f88cc9b1376a0204ffcbdb2a" "c136fb48ba65f347fbaf75c636d399bc" "f7aee835421dbeaf5d1feee5556043b6" "c0fdaa4e6087e3eba9943454ca38c68b")) (3) 0 () 0 () () (q 16 64 32 4))
