;; This file was generated by the `with-cache` library on 2017-05-09
((("6278ce06ef7ce26010ae18fb3b5193c2" "2af2e0a3542ae25aa108dd23436a0e87" "fb6bb9e3065958dc39be82a65e3067c4")) (3) 0 () 0 () () (q 128 32 128))
