;; This file was generated by the `with-cache` library on 2017-04-03
(((nqueens ("main.py" "5e003a24e56bf20c1789e3dee3222c53"))) (3) 0 () 0 () () (f python-info nqueens (c (f module-info main (c (f function-info permutations (c (f field-info iterable (u . "List(int)"))) (u . "List(List(int))")) c (f function-info n_queens (c (f field-info queen_count (u . "int"))) (u . "List(List(int))"))) ()))))
